# Generated by Django 5.0.6 on 2025-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_order_status_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
